---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: in-cluster-example
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: in-cluster-example
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: in-cluster-example
  namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  name: in-cluster-example
  namespace: default
spec:
  restartPolicy: Never
  serviceAccountName: in-cluster-example
  containers:
  - name: in-cluster-example
    image: in-cluster-example:latest
    imagePullPolicy: Never
    command:
    - in-cluster-example
